name: one-relator-curvature

channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.7
  - mpmath
  - gmpy2
  - pip

  - pip:
    - sqlalchemy
    - pulp
    - matplotlib
    - networkx
    - scipy
    - pandas
    - networkx

