name: one-relator-curvature

channels:
  - conda-forge
  - defaults
  - ibmdecisionoptimization

dependencies:
  - mpmath
  - gmpy2
  - cplex
  - pip
  
  - pip:
    - sqlalchemy
    - pulp
    - matplotlib
    - pandas
    - networkx

